// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/bezjen/gophkeeper/api/gophkeeper/v1"
)

// GophKeeperClient is an autogenerated mock type for the GophKeeperClient type
type GophKeeperClient struct {
	mock.Mock
}

// DeleteData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) DeleteData(ctx context.Context, in *v1.DeleteRequest, opts ...grpc.CallOption) (*v1.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteData")
	}

	var r0 *v1.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.DeleteRequest, ...grpc.CallOption) (*v1.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.DeleteRequest, ...grpc.CallOption) *v1.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) ListData(ctx context.Context, in *v1.ListRequest, opts ...grpc.CallOption) (*v1.ListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListData")
	}

	var r0 *v1.ListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ListRequest, ...grpc.CallOption) (*v1.ListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.ListRequest, ...grpc.CallOption) *v1.ListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.ListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Login(ctx context.Context, in *v1.LoginRequest, opts ...grpc.CallOption) (*v1.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *v1.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) (*v1.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) *v1.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Ping(ctx context.Context, in *v1.PingRequest, opts ...grpc.CallOption) (*v1.PingResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *v1.PingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PingRequest, ...grpc.CallOption) (*v1.PingResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PingRequest, ...grpc.CallOption) *v1.PingResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.PingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PingRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Register(ctx context.Context, in *v1.RegisterRequest, opts ...grpc.CallOption) (*v1.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *v1.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) (*v1.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) *v1.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) RetrieveData(ctx context.Context, in *v1.RetrieveRequest, opts ...grpc.CallOption) (*v1.RetrieveResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveData")
	}

	var r0 *v1.RetrieveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RetrieveRequest, ...grpc.CallOption) (*v1.RetrieveResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RetrieveRequest, ...grpc.CallOption) *v1.RetrieveResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RetrieveResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RetrieveRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) StoreData(ctx context.Context, in *v1.StoreRequest, opts ...grpc.CallOption) (*v1.StoreResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StoreData")
	}

	var r0 *v1.StoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.StoreRequest, ...grpc.CallOption) (*v1.StoreResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.StoreRequest, ...grpc.CallOption) *v1.StoreResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.StoreRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sync provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Sync(ctx context.Context, in *v1.SyncRequest, opts ...grpc.CallOption) (*v1.SyncResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *v1.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SyncRequest, ...grpc.CallOption) (*v1.SyncResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.SyncRequest, ...grpc.CallOption) *v1.SyncResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.SyncRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGophKeeperClient creates a new instance of GophKeeperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGophKeeperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GophKeeperClient {
	mock := &GophKeeperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
