// Code generated by mockery v2.53.4. DO NOT EDIT.

package server

import (
	context "context"

	proto "github.com/bezjen/gophkeeper/pkg/proto"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockStorage) CreateUser(ctx context.Context, user *User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteData provides a mock function with given fields: ctx, userID, dataID
func (_m *MockStorage) DeleteData(ctx context.Context, userID string, dataID string) error {
	ret := _m.Called(ctx, userID, dataID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, dataID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockStorage) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsernameOrEmail provides a mock function with given fields: ctx, username, email
func (_m *MockStorage) GetUserByUsernameOrEmail(ctx context.Context, username string, email string) (*User, error) {
	ret := _m.Called(ctx, username, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsernameOrEmail")
	}

	var r0 *User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*User, error)); ok {
		return rf(ctx, username, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *User); ok {
		r0 = rf(ctx, username, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListData provides a mock function with given fields: ctx, userID, filterType
func (_m *MockStorage) ListData(ctx context.Context, userID string, filterType proto.DataType) ([]*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, filterType)

	if len(ret) == 0 {
		panic("no return value specified for ListData")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, proto.DataType) ([]*proto.DataRecord, error)); ok {
		return rf(ctx, userID, filterType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, proto.DataType) []*proto.DataRecord); ok {
		r0 = rf(ctx, userID, filterType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, proto.DataType) error); ok {
		r1 = rf(ctx, userID, filterType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStorage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSync provides a mock function with given fields: ctx, userID, localChanges, lastSync
func (_m *MockStorage) ProcessSync(ctx context.Context, userID string, localChanges []*proto.DataRecord, lastSync int64) ([]*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, localChanges, lastSync)

	if len(ret) == 0 {
		panic("no return value specified for ProcessSync")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*proto.DataRecord, int64) ([]*proto.DataRecord, error)); ok {
		return rf(ctx, userID, localChanges, lastSync)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []*proto.DataRecord, int64) []*proto.DataRecord); ok {
		r0 = rf(ctx, userID, localChanges, lastSync)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []*proto.DataRecord, int64) error); ok {
		r1 = rf(ctx, userID, localChanges, lastSync)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveData provides a mock function with given fields: ctx, userID, dataID
func (_m *MockStorage) RetrieveData(ctx context.Context, userID string, dataID string) (*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, dataID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveData")
	}

	var r0 *proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*proto.DataRecord, error)); ok {
		return rf(ctx, userID, dataID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *proto.DataRecord); ok {
		r0 = rf(ctx, userID, dataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, dataID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreData provides a mock function with given fields: ctx, userID, data
func (_m *MockStorage) StoreData(ctx context.Context, userID string, data *proto.DataRecord) error {
	ret := _m.Called(ctx, userID, data)

	if len(ret) == 0 {
		panic("no return value specified for StoreData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *proto.DataRecord) error); ok {
		r0 = rf(ctx, userID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
