// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/bezjen/gophkeeper/pkg/proto"
)

// GophKeeperClient is an autogenerated mock type for the GophKeeperClient type
type GophKeeperClient struct {
	mock.Mock
}

// DeleteData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) DeleteData(ctx context.Context, in *proto.DeleteRequest, opts ...grpc.CallOption) (*proto.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteData")
	}

	var r0 *proto.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) (*proto.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) *proto.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) ListData(ctx context.Context, in *proto.ListRequest, opts ...grpc.CallOption) (*proto.ListResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListData")
	}

	var r0 *proto.ListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListRequest, ...grpc.CallOption) (*proto.ListResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListRequest, ...grpc.CallOption) *proto.ListResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Login(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *proto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Ping(ctx context.Context, in *proto.PingRequest, opts ...grpc.CallOption) (*proto.PingResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *proto.PingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.PingRequest, ...grpc.CallOption) (*proto.PingResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.PingRequest, ...grpc.CallOption) *proto.PingResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.PingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.PingRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Register(ctx context.Context, in *proto.RegisterRequest, opts ...grpc.CallOption) (*proto.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *proto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) (*proto.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) *proto.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) RetrieveData(ctx context.Context, in *proto.RetrieveRequest, opts ...grpc.CallOption) (*proto.RetrieveResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveData")
	}

	var r0 *proto.RetrieveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RetrieveRequest, ...grpc.CallOption) (*proto.RetrieveResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RetrieveRequest, ...grpc.CallOption) *proto.RetrieveResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RetrieveResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RetrieveRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreData provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) StoreData(ctx context.Context, in *proto.StoreRequest, opts ...grpc.CallOption) (*proto.StoreResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StoreData")
	}

	var r0 *proto.StoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.StoreRequest, ...grpc.CallOption) (*proto.StoreResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.StoreRequest, ...grpc.CallOption) *proto.StoreResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.StoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.StoreRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Sync provides a mock function with given fields: ctx, in, opts
func (_m *GophKeeperClient) Sync(ctx context.Context, in *proto.SyncRequest, opts ...grpc.CallOption) (*proto.SyncResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *proto.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) (*proto.SyncResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) *proto.SyncResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.SyncRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGophKeeperClient creates a new instance of GophKeeperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGophKeeperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GophKeeperClient {
	mock := &GophKeeperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
