// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	config "github.com/bezjen/gophkeeper/internal/client/config"
	mock "github.com/stretchr/testify/mock"
)

// ManagerInterface is an autogenerated mock type for the ManagerInterface type
type ManagerInterface struct {
	mock.Mock
}

// GetDataDir provides a mock function with no fields
func (_m *ManagerInterface) GetDataDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDataDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LoadClientConfig provides a mock function with no fields
func (_m *ManagerInterface) LoadClientConfig() (*config.ClientConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadClientConfig")
	}

	var r0 *config.ClientConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*config.ClientConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *config.ClientConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.ClientConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadSyncConfig provides a mock function with no fields
func (_m *ManagerInterface) LoadSyncConfig() (*config.SyncConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadSyncConfig")
	}

	var r0 *config.SyncConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*config.SyncConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *config.SyncConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.SyncConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveClientConfig provides a mock function with given fields: _a0
func (_m *ManagerInterface) SaveClientConfig(_a0 *config.ClientConfig) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SaveClientConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.ClientConfig) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveSyncConfig provides a mock function with given fields: _a0
func (_m *ManagerInterface) SaveSyncConfig(_a0 *config.SyncConfig) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.SyncConfig) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewManagerInterface creates a new instance of ManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagerInterface {
	mock := &ManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
