// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	proto "github.com/bezjen/gophkeeper/api/gophkeeper/v1"
	mock "github.com/stretchr/testify/mock"
)

// StoreInterface is an autogenerated mock type for the StoreInterface type
type StoreInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *StoreInterface) Get(id string) (*proto.DataRecord, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*proto.DataRecord, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *proto.DataRecord); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChangedSince provides a mock function with given fields: timestamp
func (_m *StoreInterface) GetChangedSince(timestamp int64) ([]*proto.DataRecord, error) {
	ret := _m.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for GetChangedSince")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*proto.DataRecord, error)); ok {
		return rf(timestamp)
	}
	if rf, ok := ret.Get(0).(func(int64) []*proto.DataRecord); ok {
		r0 = rf(timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(timestamp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: filterType
func (_m *StoreInterface) List(filterType proto.DataType) ([]*proto.DataRecord, error) {
	ret := _m.Called(filterType)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(proto.DataType) ([]*proto.DataRecord, error)); ok {
		return rf(filterType)
	}
	if rf, ok := ret.Get(0).(func(proto.DataType) []*proto.DataRecord); ok {
		r0 = rf(filterType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(proto.DataType) error); ok {
		r1 = rf(filterType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: record
func (_m *StoreInterface) Save(record *proto.DataRecord) error {
	ret := _m.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*proto.DataRecord) error); ok {
		r0 = rf(record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sync provides a mock function with given fields: records
func (_m *StoreInterface) Sync(records []*proto.DataRecord) error {
	ret := _m.Called(records)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*proto.DataRecord) error); ok {
		r0 = rf(records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStoreInterface creates a new instance of StoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreInterface {
	mock := &StoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
