// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/bezjen/gophkeeper/api/gophkeeper/v1"
	mock "github.com/stretchr/testify/mock"
)

// DataStorage is an autogenerated mock type for the DataStorage type
type DataStorage struct {
	mock.Mock
}

// DeleteData provides a mock function with given fields: ctx, userID, dataID
func (_m *DataStorage) DeleteData(ctx context.Context, userID string, dataID string) error {
	ret := _m.Called(ctx, userID, dataID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, dataID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListData provides a mock function with given fields: ctx, userID, filterType
func (_m *DataStorage) ListData(ctx context.Context, userID string, filterType proto.DataType) ([]*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, filterType)

	if len(ret) == 0 {
		panic("no return value specified for ListData")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, proto.DataType) ([]*proto.DataRecord, error)); ok {
		return rf(ctx, userID, filterType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, proto.DataType) []*proto.DataRecord); ok {
		r0 = rf(ctx, userID, filterType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, proto.DataType) error); ok {
		r1 = rf(ctx, userID, filterType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ping provides a mock function with given fields: ctx
func (_m *DataStorage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessSync provides a mock function with given fields: ctx, userID, localChanges, lastSync
func (_m *DataStorage) ProcessSync(ctx context.Context, userID string, localChanges []*proto.DataRecord, lastSync int64) ([]*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, localChanges, lastSync)

	if len(ret) == 0 {
		panic("no return value specified for ProcessSync")
	}

	var r0 []*proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*proto.DataRecord, int64) ([]*proto.DataRecord, error)); ok {
		return rf(ctx, userID, localChanges, lastSync)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []*proto.DataRecord, int64) []*proto.DataRecord); ok {
		r0 = rf(ctx, userID, localChanges, lastSync)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []*proto.DataRecord, int64) error); ok {
		r1 = rf(ctx, userID, localChanges, lastSync)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveData provides a mock function with given fields: ctx, userID, dataID
func (_m *DataStorage) RetrieveData(ctx context.Context, userID string, dataID string) (*proto.DataRecord, error) {
	ret := _m.Called(ctx, userID, dataID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveData")
	}

	var r0 *proto.DataRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*proto.DataRecord, error)); ok {
		return rf(ctx, userID, dataID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *proto.DataRecord); ok {
		r0 = rf(ctx, userID, dataID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DataRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, dataID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreData provides a mock function with given fields: ctx, userID, data
func (_m *DataStorage) StoreData(ctx context.Context, userID string, data *proto.DataRecord) error {
	ret := _m.Called(ctx, userID, data)

	if len(ret) == 0 {
		panic("no return value specified for StoreData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *proto.DataRecord) error); ok {
		r0 = rf(ctx, userID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDataStorage creates a new instance of DataStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *DataStorage {
	mock := &DataStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
